import { type NextPage } from "next";
import Head from "next/head";
import { LoremIpsum } from "@/components/LoremIpsum";
import { Footer } from "@/components/Footer";
import { motion, useScroll, useSpring } from "framer-motion";

const Home: NextPage = () => {
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center justify-center">
        <motion.div style={{ scaleX, position: `fixed`, top: `0`, left: `0`, right: `0`, height: `10px`, background: `red`, transformOrigin: `0%`}} />
        <h1 className="text-4xl font-bold tracking-tight text-center my-24 mt-40">
          <code >useScroll</code> demo
        </h1>
        <LoremIpsum />
      </div>
      <Footer />
    </>
  );
};

export default Home;