const paragraphContents = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac rhoncus quam. Duis ultricies pellentesque magna, a pretium leo ultricies ut. Nulla facilisi. Mauris id nibh ac urna tempor ultricies. Curabitur sit amet nisl nec mauris feugiat commodo. Proin ut urna eu est luctus lobortis id non leo. Suspendisse potenti. Vivamus venenatis feugiat mi, nec auctor nisl eleifend non. Mauris aliquet rutrum justo vel dapibus.",
    "Sed pellentesque elit nec lorem tincidunt malesuada. Fusce consequat fringilla felis a posuere. In rhoncus mi at risus efficitur, at elementum lorem tincidunt. Integer a orci sed tellus pulvinar dapibus in eget lectus. Sed et risus aliquet, vulputate massa et, malesuada est. Morbi pharetra varius ligula, nec finibus massa interdum id. Curabitur tincidunt nulla at neque dignissim, non consequat tortor faucibus. Vestibulum vulputate viverra ipsum ut faucibus.",
    "Phasellus maximus justo in consectetur dignissim. Donec at elit a purus fermentum suscipit. Maecenas id libero sem. Duis sollicitudin commodo lacus non iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce tincidunt eleifend sem, ut tincidunt justo volutpat et. Etiam consectetur cursus lorem, et euismod massa rhoncus vel. Praesent porttitor libero eget risus gravida, ut semper ipsum finibus. Nam in finibus mauris.",
    "Vestibulum efficitur velit a dolor consectetur cursus. Nullam dignissim risus a purus tempor tempus. Morbi sed consectetur turpis. Sed condimentum, purus ac semper euismod, tellus diam cursus leo, sit amet sollicitudin dolor dui ac lacus. Mauris bibendum leo a sem facilisis, nec fringilla mauris rhoncus. Fusce efficitur diam augue, nec fermentum leo lobortis vitae. Pellentesque mollis odio a ligula viverra posuere. Donec pharetra leo ac rutrum iaculis.",
    "Integer vel ipsum vel odio volutpat convallis vel sit amet eros. Mauris nec efficitur enim. Aenean interdum, tellus non lacinia sollicitudin, odio nisi posuere nunc, at finibus sem dolor a est. Cras nec leo elit. Phasellus hendrerit lectus nec tortor tristique lobortis. Nunc fermentum tincidunt sapien, sed tincidunt tellus pharetra nec. Pellentesque accumsan massa enim, ut cursus est tincidunt ut. Integer volutpat erat non lorem vulputate auctor.",
    "Cras sed diam aliquet, sollicitudin orci et, viverra enim. Vestibulum ac ultricies leo. Nulla faucibus commodo felis, et tincidunt purus efficitur non. Sed consequat tortor eu libero semper, vel hendrerit leo cursus. Fusce commodo, massa ac rhoncus malesuada, lectus metus rhoncus dolor, vitae tincidunt sapien nulla sed nunc. Sed eleifend nisl ac lorem laoreet, vitae lacinia orci facilisis. Nam sollicitudin metus a justo tristique, vitae sollicitudin lacus lobortis.",
    "Morbi sed massa bibendum, venenatis elit eget, tincidunt libero. Integer aliquet lacus et tempor malesuada. Nullam aliquet eu nisl ac laoreet. Curabitur fringilla magna ut lorem dictum, id dignissim urna rutrum. Proin pharetra consequat felis, ac semper quam posuere vitae. Sed malesuada, sem vel ultricies ullamcorper, risus dui hendrerit tellus, id congue diam diam ut velit. Phasellus id rhoncus libero. Mauris tincidunt tincidunt nibh, non posuere neque gravida id.",
    "Aliquam ullamcorper ligula sit amet mi semper ultrices. Donec vel interdum tellus. Ut tincidunt consequat quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed cursus sagittis magna. Sed tincidunt congue posuere. Cras ultricies consequat justo sed dignissim. Nam vulputate metus non ligula consectetur, vel congue enim suscipit. Vestibulum laoreet mi augue, sit amet dignissim nisi feugiat id.",
    "Vivamus non efficitur nunc. Morbi elementum nibh quis ligula laoreet iaculis. Maecenas eu semper purus. Ut id neque feugiat, convallis lacus ac, efficitur mi. Sed condimentum malesuada orci ut convallis. Duis hendrerit sem sed turpis dictum semper. Aenean venenatis purus non velit iaculis aliquet. Sed fringilla ullamcorper massa, vitae pharetra dolor commodo a. Fusce dignissim urna vel nulla laoreet cursus.",
    "Pellentesque at lorem malesuada, eleifend velit id, aliquam purus. Nulla facilisi. Sed consequat, nisl ut mattis vestibulum, risus elit varius dolor, id ullamcorper metus felis vel elit. In pharetra massa non sapien scelerisque, eget viverra justo rutrum. Integer congue risus non turpis tempor efficitur. Ut id lectus nec justo iaculis varius. Nam malesuada purus nec lectus vestibulum feugiat. Duis auctor, tellus et vestibulum consequat, sapien orci tempor arcu, sed cursus nisi sem ut dui."
  ];

export default paragraphContents